# Generated by Django 5.0.7 on 2024-08-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите тему сообщения', max_length=150, verbose_name='Тема сообщения')),
                ('body', models.TextField(help_text='Введите сообщение', verbose_name='Сообщение')),
            ],
        ),
    ]
