# Generated by Django 5.0.7 on 2024-08-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_alter_message_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Введите название рассылки', max_length=150, null=True, verbose_name='Название рассылки')),
                ('description', models.TextField(blank=True, help_text='Введите описание рассылки', null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Введите дату создания статьи', verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ('created_at',),
            },
        ),
    ]
