# Generated by Django 5.0.7 on 2024-08-05 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_mailingsettings_alter_message_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите имя клиента', max_length=150, verbose_name='Имя клиента')),
                ('email', models.EmailField(help_text='Введите email клиента', max_length=254, verbose_name='Email клиента')),
                ('comment', models.TextField(help_text='Введите комментарий', verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('mailing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mailing', to='mailing.mailing', verbose_name='рассылка')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
