# Generated by Django 5.0.7 on 2024-08-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_alter_mailingsettings_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AddField(
            model_name='mailingsettings',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время окончания рассылки'),
        ),
        migrations.AddField(
            model_name='mailingsettings',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время начала рассылки'),
        ),
    ]
