# Generated by Django 4.2.2 on 2024-08-06 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailing', '0008_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Введите имя пользователя', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message', to='mailing.message', verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='settings',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='mailing.mailingsettings', verbose_name='Настройки'),
        ),
        migrations.AlterField(
            model_name='mailingsettings',
            name='active',
            field=models.BooleanField(default=True, help_text='Запущена ли рассылка сейчас', verbose_name='Активность'),
        ),
        migrations.AlterField(
            model_name='mailingsettings',
            name='datetime_send',
            field=models.DateTimeField(auto_now_add=True, help_text='Введите дату и время первой отправки рассылки', verbose_name='Дата и время первой отправки рассылки'),
        ),
        migrations.AlterField(
            model_name='mailingsettings',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время окончания рассылки'),
        ),
        migrations.AlterField(
            model_name='mailingsettings',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время начала рассылки'),
        ),
    ]
