# Generated by Django 4.2.2 on 2024-08-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0009_mailing_user_alter_mailing_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingsettings',
            name='status_changed',
            field=models.BooleanField(default=True, help_text='Введите статус рассылки (ожидается (запущена или завершена))', verbose_name='Выбранный статус'),
        ),
    ]
