# Generated by Django 4.2.2 on 2024-08-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите заголовок статьи', max_length=255, verbose_name='Заголовок статьи')),
                ('body', models.TextField(help_text='Добавьте содержимое статьи', verbose_name='Содержимое стати')),
                ('image', models.ImageField(blank=True, help_text='Загрузите превью статьи', null=True, upload_to='blog/photo', verbose_name='Превью')),
                ('slug', models.SlugField(blank=True, help_text='slug', null=True, unique=True, verbose_name='slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Укажите дату создания', verbose_name='Дата создания')),
                ('is_published', models.BooleanField(default=True, help_text='Укажите признак публикации', verbose_name='Признак публикации')),
                ('number_views', models.PositiveIntegerField(default=0, help_text='Укажите количество просмотров', verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ('-created_at',),
            },
        ),
    ]
